version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: spring-batch-postgres
    environment:
      POSTGRES_USER: s_batch_user
      POSTGRES_PASSWORD: s_batch_password
      POSTGRES_DB: spring-batch-db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U s_batch_user -d spring-batch-db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  pgdata:

networks:
  my_network: